title: Site
pages: default
fields:
  title:
    label: Title
    type:  text
  subtitle:
    label: Subtitle
    type: text
  author:
    label: Author
    type:  text
  description:
    label: Description
    type:  textarea
  keywords:
    label: Keywords
    type:  tags
  copyright:
    label: Copyright
    type:  textarea
  phone:
    label: Phone Number
    type:  text
  email:
    label: Email
    type:  text
  address:
    label: Address
    type: textarea
  facebook:
    label: Facebook
    type:  text
  youtube:
    label: Instagram
    type:  text
  blog:
    label: Blog
    type:  text
  subscribe:
    label: Subscribe
    type:  text
  contact:
    label: Contact
    type:  text
